- name: unarchive java
  unarchive:
    src: files/java/jdk-8u131-linux-x64.tar.gz
    dest: /opt
    creates: /opt/jdk-8u131-linux-x64
  #become: yes

- name: Make Java available for system
  command: 'alternatives --install "/usr/bin/java" "java" "/opt/jdk1.8.0_131/bin/java" 2000'
  #become: yes
